# Day 5: Hydrothermal Venture

## Part 1:

You come across a field of hydrothermal vents on the ocean floor! These vents constantly produce large, opaque clouds, so it would be best to avoid them if possible.

They tend to form in lines; the submarine helpfully produces a list of nearby lines of vents (your puzzle input) for you to review. For example:
```
0,9 -> 5,9
8,0 -> 0,8
9,4 -> 3,4
2,2 -> 2,1
7,0 -> 7,4
6,4 -> 2,0
0,9 -> 2,9
3,4 -> 1,4
0,0 -> 8,8
5,5 -> 8,2
```
Each line of vents is given as a line segment in the format x1,y1 -> x2,y2 where x1,y1 are the coordinates of one end the line segment and x2,y2 are the coordinates of the other end. These line segments include the points at both ends. In other words:

An entry like 1,1 -> 1,3 covers points 1,1, 1,2, and 1,3.
An entry like 9,7 -> 7,7 covers points 9,7, 8,7, and 7,7.
For now, only consider horizontal and vertical lines: lines where either x1 = x2 or y1 = y2.

So, the horizontal and vertical lines from the above list would produce the following diagram:
```
.......1..
..1....1..
..1....1..
.......1..
.112111211
..........
..........
..........
..........
222111....
```
In this diagram, the top left corner is 0,0 and the bottom right corner is 9,9. Each position is shown as the number of lines which cover that point or . if no line covers that point. The top-left pair of 1s, for example, comes from 2,2 -> 2,1; the very bottom row is formed by the overlapping lines 0,9 -> 5,9 and 0,9 -> 2,9.

To avoid the most dangerous areas, you need to determine the number of points where at least two lines overlap. In the above example, this is anywhere in the diagram with a 2 or larger - a total of 5 points.

Consider only horizontal and vertical lines. **At how many points do at least two lines overlap?**

In [6]:
# Get test input
with open('./test_input_5.txt') as f:
    lines = f.readlines()
test_input = [line.strip() for line in lines]
test_input

['0,9 -> 5,9',
 '8,0 -> 0,8',
 '9,4 -> 3,4',
 '2,2 -> 2,1',
 '7,0 -> 7,4',
 '6,4 -> 2,0',
 '0,9 -> 2,9',
 '3,4 -> 1,4',
 '0,0 -> 8,8',
 '5,5 -> 8,2']

This feels very similar to how I marked the bingo boards on yesterday's puzzle:
```
# Return number of draws to win with a board
def score_board(drawing, board):
    rows = [0]*len(board)
    cols = [0]*len(board)
    for i, num in enumerate(drawing):
        try:
            x, y = np.argwhere(board == num)[0]
            rows[x]+=1
            cols[y]+=1
            if 5 in rows or 5 in cols:
                return i+1
            else:
                continue
        except:
            continue
```

In [25]:
test_line = test_input[0]
test_line

'0,9 -> 5,9'

In [57]:
coord_pairs = [list(map(int, x.split(','))) for x in test_line.replace(' ','').split('->')]
coord_pairs

[[0, 9], [5, 9]]

In [58]:
np.max(coord_pairs)

9

In [41]:
import numpy as np

In [43]:
np.max(np.array(coord_pairs))

9

I need to find the max x-coord and max y-coord, can't assume they're the same--although I could take the lazy way and just take the absolute max, but that would waste a lot of space. Might just do it to at least get off the ground though.

In [45]:
np.matrix(coord_pairs)

matrix([[0, 9],
        [5, 9]])

In [63]:
min(0, 5)

0

In [66]:
def solution(input_text):
    # Parse into coordinate pairs
    coord_pairs = []
    for line in input_text:
        coord_pairs.append([list(map(int, x.split(','))) for x in line.replace(' ','').split('->')])
    
    # Initialize grid
    grid = np.zeros((np.max(coord_pairs), np.max(coord_pairs)))
    
    for pair in coord_pairs:
        # Vertical line
        if pair[0][0] == pair[1][0]:
            x = pair[0][0] - 1
            start = min(pair[0][1], pair[1][1]) - 1
            stop = max(pair[0][1], pair[1][1])
            for i in range(start, stop+1):
                grid[x][i] += 1
        
        # Horizontal line
        elif pair[0][1] == pair[1][1]:
            y = pair[0][1] - 1
            start = min(pair[0][0], pair[1][0]) - 1
            stop = max(pair[0][0], pair[1][0])
            for i in range(start, stop+1):
                grid[i][y] += 1
        
        # Angled line
        else:
            continue
        
        print(grid)
        
        return
        
        
        

In [67]:
solution(test_input)

[[0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [46]:
# Get full input
with open('./input_5.txt') as f:
    lines = f.readlines()
full_input = [line.strip() for line in lines]
full_input

['72,504 -> 422,154',
 '877,851 -> 680,654',
 '447,989 -> 517,989',
 '173,125 -> 981,933',
 '736,255 -> 374,617',
 '835,681 -> 693,539',
 '451,176 -> 451,885',
 '793,629 -> 793,157',
 '907,945 -> 47,85',
 '868,104 -> 892,104',
 '594,18 -> 384,18',
 '454,880 -> 524,880',
 '400,271 -> 915,271',
 '843,989 -> 45,191',
 '640,885 -> 845,885',
 '115,370 -> 115,633',
 '185,578 -> 185,648',
 '159,929 -> 933,155',
 '650,147 -> 650,523',
 '719,72 -> 719,649',
 '908,80 -> 18,970',
 '417,246 -> 777,606',
 '452,803 -> 170,803',
 '311,324 -> 18,324',
 '665,835 -> 108,278',
 '654,122 -> 223,122',
 '38,40 -> 38,713',
 '658,471 -> 148,471',
 '894,783 -> 894,693',
 '461,950 -> 941,470',
 '234,542 -> 941,542',
 '441,793 -> 291,793',
 '913,139 -> 302,139',
 '978,24 -> 50,952',
 '817,828 -> 374,385',
 '919,68 -> 919,819',
 '674,20 -> 722,20',
 '950,698 -> 312,60',
 '350,398 -> 213,398',
 '93,627 -> 93,896',
 '629,296 -> 118,296',
 '324,372 -> 324,83',
 '125,130 -> 543,130',
 '29,40 -> 29,262',
 '297,682 -> 

In [49]:
coord_pairs.clear()

In [50]:
for line in full_input:
    coord_pairs.append([list(map(int, x.split(','))) for x in line.replace(' ','').split('->')])
coord_pairs

[[[72, 504], [422, 154]],
 [[877, 851], [680, 654]],
 [[447, 989], [517, 989]],
 [[173, 125], [981, 933]],
 [[736, 255], [374, 617]],
 [[835, 681], [693, 539]],
 [[451, 176], [451, 885]],
 [[793, 629], [793, 157]],
 [[907, 945], [47, 85]],
 [[868, 104], [892, 104]],
 [[594, 18], [384, 18]],
 [[454, 880], [524, 880]],
 [[400, 271], [915, 271]],
 [[843, 989], [45, 191]],
 [[640, 885], [845, 885]],
 [[115, 370], [115, 633]],
 [[185, 578], [185, 648]],
 [[159, 929], [933, 155]],
 [[650, 147], [650, 523]],
 [[719, 72], [719, 649]],
 [[908, 80], [18, 970]],
 [[417, 246], [777, 606]],
 [[452, 803], [170, 803]],
 [[311, 324], [18, 324]],
 [[665, 835], [108, 278]],
 [[654, 122], [223, 122]],
 [[38, 40], [38, 713]],
 [[658, 471], [148, 471]],
 [[894, 783], [894, 693]],
 [[461, 950], [941, 470]],
 [[234, 542], [941, 542]],
 [[441, 793], [291, 793]],
 [[913, 139], [302, 139]],
 [[978, 24], [50, 952]],
 [[817, 828], [374, 385]],
 [[919, 68], [919, 819]],
 [[674, 20], [722, 20]],
 [[950, 698], [312,

In [53]:
np.max(np.array(coord_pairs))

989

## Part 2:

