# Day 4: Giant Squid

## Part 1:

You're already almost 1.5km (almost a mile) below the surface of the ocean, already so deep that you can't see any sunlight. What you **can** see, however, is a giant squid that has attached itself to the outside of your submarine.

Maybe it wants to play [bingo](https://en.wikipedia.org/wiki/Bingo_(American_version))?

Bingo is played on a set of boards each consisting of a 5x5 grid of numbers. Numbers are chosen at random, and the chosen number is marked on all boards on which it appears. (Numbers may not appear on all boards.) If all numbers in any row or any column of a board are marked, that board wins. (Diagonals don't count.)

The submarine has a bingo subsystem to help passengers (currently, you and the giant squid) pass the time. It automatically generates a random order in which to draw numbers and a random set of boards (your puzzle input). For example:

```
7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1

22 13 17 11  0
 8  2 23  4 24
21  9 14 16  7
 6 10  3 18  5
 1 12 20 15 19

 3 15  0  2 22
 9 18 13 17  5
19  8  7 25 23
20 11 10 24  4
14 21 16 12  6

14 21 17 24  4
10 16 15  9 19
18  8 23 26 20
22 11 13  6  5
 2  0 12  3  7
 ```
 
After the first five numbers are drawn (7, 4, 9, 5, and 11), there are no winners, but the boards are marked as follows (shown here adjacent to each other to save space):
```
22 13 17 11  0         3 15  0  2 22        14 21 17 24  4
 8  2 23  4 24         9 18 13 17  5        10 16 15  9 19
21  9 14 16  7        19  8  7 25 23        18  8 23 26 20
 6 10  3 18  5        20 11 10 24  4        22 11 13  6  5
 1 12 20 15 19        14 21 16 12  6         2  0 12  3  7
 ```
After the next six numbers are drawn (17, 23, 2, 0, 14, and 21), there are still no winners:
```
22 13 17 11  0         3 15  0  2 22        14 21 17 24  4
 8  2 23  4 24         9 18 13 17  5        10 16 15  9 19
21  9 14 16  7        19  8  7 25 23        18  8 23 26 20
 6 10  3 18  5        20 11 10 24  4        22 11 13  6  5
 1 12 20 15 19        14 21 16 12  6         2  0 12  3  7
 ```
Finally, 24 is drawn:
```
22 13 17 11  0         3 15  0  2 22        14 21 17 24  4
 8  2 23  4 24         9 18 13 17  5        10 16 15  9 19
21  9 14 16  7        19  8  7 25 23        18  8 23 26 20
 6 10  3 18  5        20 11 10 24  4        22 11 13  6  5
 1 12 20 15 19        14 21 16 12  6         2  0 12  3  7
 ```
At this point, the third board **wins** because it has at least one complete row or column of marked numbers (in this case, the entire top row is marked: `14 21 17 24 4`).

The score of the winning board can now be calculated. Start by finding the **sum of all unmarked numbers on that board**; in this case, the sum is `188`. Then, multiply that sum by **the number that was just called** when the board won, 24, to get the final score, `188 * 24 = 4512`.

To guarantee victory against the giant squid, figure out which board will win first. **What will your final score be if you choose that board?**

Pseudocode solution:
```
def solution(input_text):
    drawing = get_drawing_numbers(input_text)
    boards = get_boards(input_text)
    
    for num in drawing:
        if check_winner(boards):
            return score(winning_board(boards))
        else:
            mark_boards(num)
```

In [296]:
# First on the test input
with open('./test_input_4.txt') as f:
    lines = f.readlines()
test_bingo = [line.strip() for line in lines]
test_bingo

['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1',
 '',
 '22 13 17 11  0',
 '8  2 23  4 24',
 '21  9 14 16  7',
 '6 10  3 18  5',
 '1 12 20 15 19',
 '',
 '3 15  0  2 22',
 '9 18 13 17  5',
 '19  8  7 25 23',
 '20 11 10 24  4',
 '14 21 16 12  6',
 '',
 '14 21 17 24  4',
 '10 16 15  9 19',
 '18  8 23 26 20',
 '22 11 13  6  5',
 '2  0 12  3  7']

First step is definitely to get this into one set of drawing numbers and a bunch of bingo boards.

In [155]:
test_bingo[0]

'7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1'

In [156]:
drawing = [int(num) for num in test_bingo[0].split(',')]
drawing

[7,
 4,
 9,
 5,
 11,
 17,
 23,
 2,
 0,
 14,
 21,
 24,
 10,
 16,
 13,
 6,
 15,
 25,
 12,
 22,
 18,
 20,
 8,
 19,
 3,
 26,
 1]

To get the boards, I want to iterate down through the input text, loading a board after each newline. It will probably help to know in advance that all boards are 5x5. It sounds like it might be easy to save them all as either nested lists/dicts or numpy arrays/matrix.

In [157]:
import numpy as np

In [158]:
test_bingo[2:7]

['22 13 17 11  0',
 '8  2 23  4 24',
 '21  9 14 16  7',
 '6 10  3 18  5',
 '1 12 20 15 19']

In [159]:
test_array = np.zeros((5, 5))
test_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [160]:
test_array[0] = [1, 2, 3, 4, 5]
test_array

array([[1., 2., 3., 4., 5.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [161]:
test_bingo[2].split()

['22', '13', '17', '11', '0']

In [184]:
for line in test_bingo[1:]:
    if line == '':
        print('Blank line!')
    else:
        print(line)

Blank line!
22 13 17 11  0
8  2 23  4 24
21  9 14 16  7
6 10  3 18  5
1 12 20 15 19
Blank line!
3 15  0  2 22
9 18 13 17  5
19  8  7 25 23
20 11 10 24  4
14 21 16 12  6
Blank line!
14 21 17 24  4
10 16 15  9 19
18  8 23 26 20
22 11 13  6  5
2  0 12  3  7


In [188]:
boards = []
new_board = []

for line in test_bingo[2:]:
    if line == '' or line == test_bingo[-1]:
        boards.append(new_board)
        new_board = []
    else:
        new_line = [int(num) for num in line.split()]
        new_board.append(new_line)

boards

[[[22, 13, 17, 11, 0],
  [8, 2, 23, 4, 24],
  [21, 9, 14, 16, 7],
  [6, 10, 3, 18, 5],
  [1, 12, 20, 15, 19]],
 [[3, 15, 0, 2, 22],
  [9, 18, 13, 17, 5],
  [19, 8, 7, 25, 23],
  [20, 11, 10, 24, 4],
  [14, 21, 16, 12, 6]],
 [[14, 21, 17, 24, 4],
  [10, 16, 15, 9, 19],
  [18, 8, 23, 26, 20],
  [22, 11, 13, 6, 5]]]

Actually, after taking a walk and a break, I'm realizing that my original approach is quite inefficient and I think I have a better idea:

```
def solution(input_text):
    drawing = get_drawing_numbers(input_text)
    best_board = []
    # Initialize with worst possible game
    fastest_win = len(drawing) 
    
    while input_text:
        board = get_next_board(input_text) # Destructive; input_text becomes Null
        draws_to_win = score_board(board)
        if draws_to_win = 5 # Fastest possible game
            best_board = board
            break
        elif draws_to_win < fastest_win:
            best_board = board
            fastest_win = draw_to_win
        else:
            continue
    
    return final_score(best_board) * drawing[fastest_win]
```

In [301]:
test_bingo[2:7]

['22 13 17 11  0',
 '8  2 23  4 24',
 '21  9 14 16  7',
 '6 10  3 18  5',
 '1 12 20 15 19']

In [302]:
test_board = test_bingo[2:7]
test_board

['22 13 17 11  0',
 '8  2 23  4 24',
 '21  9 14 16  7',
 '6 10  3 18  5',
 '1 12 20 15 19']

In [303]:
new_board = []
for i in range(5):
    new_board.append(np.array([int(num) for num in test_board.pop(0).split()]))
new_board = np.array(new_board)
new_board

array([[22, 13, 17, 11,  0],
       [ 8,  2, 23,  4, 24],
       [21,  9, 14, 16,  7],
       [ 6, 10,  3, 18,  5],
       [ 1, 12, 20, 15, 19]])

In [310]:
np.argwhere(new_board==19)[0]

array([4, 4])

In [319]:
# Return next board from input_text as 2D numpy array
def get_next_board(input_text):
    # Get rid of first blank line
    blank = input_text.pop(0)
    new_board = []
    for i in range(5):
        new_board.append(np.array([int(num) for num in input_text.pop(0).split()]))
    return np.array(new_board)

In [426]:
# Return number of draws to win with a board
def score_board(drawing, board):
    rows = [0]*len(board)
    cols = [0]*len(board)
    for i, num in enumerate(drawing):
        try:
            x, y = np.argwhere(board == num)[0]
            rows[x]+=1
            cols[y]+=1
            if 5 in rows or 5 in cols:
                return i+1
            else:
                continue
        except:
            continue

In [427]:
def final_score(drawing, board, fastest_win):
    flat_board = board.flatten()
    remainder = [num for num in flat_board if num not in drawing[:fastest_win]]
    print(remainder)
    return np.sum(remainder)

In [428]:
def solution(input_text):
    drawing = [int(num) for num in input_text.pop(0).split(',')]
    best_board = None
    fastest_win = len(drawing)
    
    while input_text:
        board = get_next_board(input_text)
        draws_to_win = score_board(drawing, board)
        # Fastest possible game
        if draws_to_win==5:
            fastest_win = draws_to_win
            best_board = board
            break
        # Faster game
        elif draws_to_win < fastest_win:
            best_board = board
            fastest_win = draws_to_win
        # Slower game
        else:
            continue
    print(fastest_win)
    print(best_board)
    print(drawing[:fastest_win])
    print(drawing[fastest_win-1])
    return final_score(drawing, best_board, fastest_win) * drawing[fastest_win-1]

In [429]:
# First on the test input
with open('./test_input_4.txt') as f:
    lines = f.readlines()
test_bingo = [line.strip() for line in lines]
test_bingo

['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1',
 '',
 '22 13 17 11  0',
 '8  2 23  4 24',
 '21  9 14 16  7',
 '6 10  3 18  5',
 '1 12 20 15 19',
 '',
 '3 15  0  2 22',
 '9 18 13 17  5',
 '19  8  7 25 23',
 '20 11 10 24  4',
 '14 21 16 12  6',
 '',
 '14 21 17 24  4',
 '10 16 15  9 19',
 '18  8 23 26 20',
 '22 11 13  6  5',
 '2  0 12  3  7']

In [430]:
solution(test_bingo)

12
[[14 21 17 24  4]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3  7]]
[7, 4, 9, 5, 11, 17, 23, 2, 0, 14, 21, 24]
24
[10, 16, 15, 19, 18, 8, 26, 20, 22, 13, 6, 12, 3]


4512

Seems like it's working!

After an hour of debugging, I realized I was getting the right answer for the wrong reason. The `score_board` function was only ever returning the number of total marked off numbers on a winning board, but *not* the actual number of draws it took to get there! (I hadn't fully accounted for drawn numbers not being present on the board!)

In [413]:
drawing = '99,56,7,15,81,26,75,40,87,59,62,24,58,34,78,86,44,65,18,94,20,17,98,29,57,92,14,32,46,79,85,84,35,68,55,22,41,61,90,11,69,96,23,47,43,80,72,50,97,33,53,25,28,51,49,64,12,63,21,48,27,19,67,88,66,45,3,71,16,70,76,13,60,77,73,1,8,10,52,38,36,74,83,2,37,6,31,91,89,54,42,30,5,82,9,95,93,4,0,39'
drawing = [int(num) for num in drawing.split(',')]
print(drawing)
test_board = get_next_board(['','60 14 37 78 73',
                            '80 40 58 30 64',
                            '77 92 81  1 45',
                            '79 26 11 12 51',
                            '25 56 68 67 61'])
test_board

[99, 56, 7, 15, 81, 26, 75, 40, 87, 59, 62, 24, 58, 34, 78, 86, 44, 65, 18, 94, 20, 17, 98, 29, 57, 92, 14, 32, 46, 79, 85, 84, 35, 68, 55, 22, 41, 61, 90, 11, 69, 96, 23, 47, 43, 80, 72, 50, 97, 33, 53, 25, 28, 51, 49, 64, 12, 63, 21, 48, 27, 19, 67, 88, 66, 45, 3, 71, 16, 70, 76, 13, 60, 77, 73, 1, 8, 10, 52, 38, 36, 74, 83, 2, 37, 6, 31, 91, 89, 54, 42, 30, 5, 82, 9, 95, 93, 4, 0, 39]


array([[60, 14, 37, 78, 73],
       [80, 40, 58, 30, 64],
       [77, 92, 81,  1, 45],
       [79, 26, 11, 12, 51],
       [25, 56, 68, 67, 61]])

In [414]:
score_board(drawing, test_board)

8

In [415]:
drawing[:8]

[99, 56, 7, 15, 81, 26, 75, 40]

In [431]:
# Now on the full input
with open('./input_4.txt') as f:
    lines = f.readlines()
bingo = [line.strip() for line in lines]
bingo

['99,56,7,15,81,26,75,40,87,59,62,24,58,34,78,86,44,65,18,94,20,17,98,29,57,92,14,32,46,79,85,84,35,68,55,22,41,61,90,11,69,96,23,47,43,80,72,50,97,33,53,25,28,51,49,64,12,63,21,48,27,19,67,88,66,45,3,71,16,70,76,13,60,77,73,1,8,10,52,38,36,74,83,2,37,6,31,91,89,54,42,30,5,82,9,95,93,4,0,39',
 '',
 '57 19 40 54 64',
 '22 69 15 88  8',
 '79 60 48 95 85',
 '34 97 33  1 55',
 '72 82 29 90 84',
 '',
 '19 17 62 78 27',
 '61 13 30 75 25',
 '14 66 72 37 79',
 '49 91 97  0 23',
 '12 52 41 92 18',
 '',
 '52 17 62 49 76',
 '8 78 93 37 12',
 '9 40 59 75 94',
 '45  2 81 44 63',
 '73 18 48 11 90',
 '',
 '59 75 55 74 43',
 '1 17 89 36 91',
 '87 52 45 83 22',
 '9  3 15 11 53',
 '94 72 68 29 20',
 '',
 '71 97 74 32 17',
 '31  5 43 83 38',
 '85 27 37 14 65',
 '23  0 61 33 82',
 '41 63 70 60  6',
 '',
 '58 24 28 42 73',
 '80 52 97 68 53',
 '30 40 45 18 13',
 '94 12  7 77 98',
 '72 14 34 21 23',
 '',
 '97 93 21 99 35',
 '31  8 73 15 74',
 '67 60 44  1 18',
 '68 61 64 82 86',
 '76 47 22 63 78',
 '',
 '49 

In [432]:
solution(bingo)

27
[[60 14 37 78 73]
 [80 40 58 30 64]
 [77 92 81  1 45]
 [79 26 11 12 51]
 [25 56 68 67 61]]
[99, 56, 7, 15, 81, 26, 75, 40, 87, 59, 62, 24, 58, 34, 78, 86, 44, 65, 18, 94, 20, 17, 98, 29, 57, 92, 14]
14
[60, 37, 73, 80, 30, 64, 77, 1, 45, 79, 11, 12, 51, 25, 68, 67, 61]


11774

FINALLY!

## Part 2:



On the other hand, it might be wise to try a different strategy: let the giant squid win.

You aren't sure how many bingo boards a giant squid could play at once, so rather than waste time counting its arms, the safe thing to do is to **figure out which board will win last** and choose that one. That way, no matter which boards it picks, it will win for sure.

In the above example, the second board is the last to win, which happens after 13 is eventually called and its middle column is completely marked. If you were to keep playing until this point, the second board would have a sum of unmarked numbers equal to 148 for a final score of 148 * 13 = 1924.

Figure out which board will win last. Once it wins, what would its final score be?

*This actually seems a pretty easy change--all I have to do is keep track of the slowest_win instead of the fastest_win!*

In [436]:
# Return next board from input_text as 2D numpy array
def get_next_board(input_text):
    # Get rid of first blank line
    blank = input_text.pop(0)
    new_board = []
    for i in range(5):
        new_board.append(np.array([int(num) for num in input_text.pop(0).split()]))
    return np.array(new_board)

# Return number of draws to win with a board
def score_board(drawing, board):
    rows = [0]*len(board)
    cols = [0]*len(board)
    for i, num in enumerate(drawing):
        try:
            x, y = np.argwhere(board == num)[0]
            rows[x]+=1
            cols[y]+=1
            if 5 in rows or 5 in cols:
                return i+1
            else:
                continue
        except:
            continue
    return

# Calculate the final score for the slowest board
def final_score(drawing, board, slowest_win):
    flat_board = board.flatten()
    remainder = [num for num in flat_board if num not in drawing[:slowest_win]]
    print(remainder)
    return np.sum(remainder)

def slowest_solution(input_text):
    drawing = [int(num) for num in input_text.pop(0).split(',')]
    worst_board = None
    slowest_win = 0
    
    while input_text:
        board = get_next_board(input_text)
        draws_to_win = score_board(drawing, board)
        # Slowest possible game
        if draws_to_win==len(drawing):
            slowest_win = draws_to_win
            worst_board = board
            break
        # Slower game
        elif draws_to_win > slowest_win:
            worst_board = board
            slowest_win = draws_to_win
        # Faster game
        else:
            continue
    print(slowest_win)
    print(worst_board)
    print(drawing[:slowest_win])
    print(drawing[slowest_win-1])
    return final_score(drawing, worst_board, slowest_win) * drawing[slowest_win-1]

In [437]:
# First on the test input
with open('./test_input_4.txt') as f:
    lines = f.readlines()
test_bingo = [line.strip() for line in lines]

slowest_solution(test_bingo)

15
[[ 3 15  0  2 22]
 [ 9 18 13 17  5]
 [19  8  7 25 23]
 [20 11 10 24  4]
 [14 21 16 12  6]]
[7, 4, 9, 5, 11, 17, 23, 2, 0, 14, 21, 24, 10, 16, 13]
13
[3, 15, 22, 18, 19, 8, 25, 20, 12, 6]


1924

In [438]:
# Now on the full input
with open('./input_4.txt') as f:
    lines = f.readlines()
bingo = [line.strip() for line in lines]

slowest_solution(bingo)

87
[[79 23 31 48 12]
 [37 96 74 63  4]
 [98 18 69  6  0]
 [47 54 34 82 46]
 [ 5 86 64 60 99]]
[99, 56, 7, 15, 81, 26, 75, 40, 87, 59, 62, 24, 58, 34, 78, 86, 44, 65, 18, 94, 20, 17, 98, 29, 57, 92, 14, 32, 46, 79, 85, 84, 35, 68, 55, 22, 41, 61, 90, 11, 69, 96, 23, 47, 43, 80, 72, 50, 97, 33, 53, 25, 28, 51, 49, 64, 12, 63, 21, 48, 27, 19, 67, 88, 66, 45, 3, 71, 16, 70, 76, 13, 60, 77, 73, 1, 8, 10, 52, 38, 36, 74, 83, 2, 37, 6, 31]
31
[4, 0, 54, 82, 5]


4495

Wow, SO much easier than Part 1! But maybe just because I set it up in a way that lent itself to making that change fairly simple.

This puzzle seemed waaaay harder than Day 3! It might just be that it had many more moving parts, or maybe I made it more complicated somehow, or missed an obvious solution. 

I'm still proud of how I handled the scoring--rather than just making a sparse matrix to mark each drawn number for each board, I was able to store the information about the state of a board during play in a set of just 2 small arrays. It's probably not a huge deal for most seasoned coders, but for me it was a leap in thinking from literally/spatially representing the state of a bingo board to a more creative/efficient solution.

I also like how my solution involves going through all the boards only *once* and only storing 2 boards at a time, whereas my initial solution meant storing *all* board in memory, then looping through all of them for every new number draw. My better solution does involves looping over drawing many times, but it's a 1D array. 

I'm very curious to know how to optimize this solution even further. I'm sure this is not the fastest/lightest way.